package jp.co.nintendo.chat.message.domain.model

import jp.co.nintendo.chat.message.domain.model.content.MessageContent
import jp.co.nintendo.chat.message.domain.model.content.system.SystemMessageErrorType

/**
 * Represents a message in a chat conversation between users and an AI assistant.
 * Provides type-safe handling of different message sources through sealed interface pattern.
 */
sealed interface ChatMessage {
    val messageId: String
    val createdAtMillis: Long

    /**
     * A [ChatMessage] sent by the user
     */
    data class User(
        override val messageId: String,
        override val createdAtMillis: Long,
        val content: MessageContent
    ) : ChatMessage

    /**
     * A [ChatMessage] generated by the AI assistant
     */
    data class AiAssistant(
        override val messageId: String,
        override val createdAtMillis: Long,
        val responseId: String,
        val content: MessageContent
    ) : ChatMessage

    /**
     * A [ChatMessage] generated by system
     */
    sealed interface System : ChatMessage {
        data class Error(
            override val messageId: String,
            override val createdAtMillis: Long,
            val errorType: SystemMessageErrorType
        ): System
    }
}
